### ISSUE TITLE
Use episode updated event to run renamer

### ISSUE THREAD

**Issue by Terrails** [Mik1ll/LuaRenamer#31]
Currently, the renamer only runs on import and thats it. Due to that episodes with a title "Episode X" are not renamed to their actual name when/if it is eventually updated. It would be a nice addition to add an option to run the renamer whenever episode info is updated.

**Comment by Mik1ll** [comment]
### TODO List/Blocking issues:
- [ ] Task: Determine whether to use IPlugin interface and DI to get the IShokoEventHandler or use reflection and grab the singleton instance ShokoEventHandler.Instance
- [ ] Task: As this feature would be opt in, and must be loaded on startup, a rename script cannot be used to configure this. A new configuration option must be created
    - Look into ISettingsProvider or creating a new config file
- [ ] Blocking: OnSeriesUpdated and OnEpisodeUpdated do not seem to be invoked anywhere within Shoko
- [ ] Blocking: IAnime and IEpisode do not provide Local Video Ids, there is no API endpoint for renaming files related to an anime or episode
    - Potential workaround: Reflection on repositories to query the local files

**Comment by Mik1ll** [comment]
[Reference plugin that utilizes IShokoEventHandler](https://github.com/fearnlj01/WebhookDump-ShokoPlugin/blob/master/WebhookDump.cs)

**Comment by Terrails** [comment]
The latest Shoko daily seems to run the renamer on this event now, so there should be no need to implement this anymore.
